### PR TITLE
Refactor rotational transformation for red alliance

### PR DESCRIPTION
**Pull request by PatribotsProgramming**
state.poseMeters.getRotation().times(-1) will return -PI when PI is inputted, but when the robot is on the opposing alliance, the rotation needs to be 0 degrees if 180 is inputted, to preserve the holonomic rotation facing the grid.

The cpp equivalent for this still needs to be made.

Co-authored-by: Alexander Hamilton <a.hamilton72006@gmail.com>

### CODE REVIEW

**Comment by PatribotsProgramming** [comment]
I should also mention that #207 should be mirrored on the X axis and not the Y, as seen in [this Cheif Delphi post](https://www.chiefdelphi.com/t/pathplanner-trajectory-mirrors-on-x-instead-of-y/423757), meaning that I should have included this change in the PR.

**Comment by GalexY727** [comment]
I had to include the java docs haha

**Comment by hadley31** [comment]
Hi @PatribotsProgramming, please read discussion #261

**Comment by mjansen4857** [comment]
> rotation needs to be 0 degrees if 180 is inputted

This is not correct. 0 Degrees is facing away from your driver driver station wall.

Also, the alliance transformation stuff is correct, so I will be closing this. If your coordinate system is different from what the WPILib standard is then you will need to implement the transformations yourself, since PPLib will follow the wpilib standards.

**Pull request closed without merging**
