### PR TITLE
Improved marker time calculation:

### PR DESCRIPTION
**Pull request by bckircher**
- Add resolution as a constant in Trajectory
- Lerp between trajectory states to find the marker time

Fixes mjansen4857/pathplanner#105

### CODE REVIEW

**Comment by mjansen4857** [comment]
I don't think the addition to path_painter_util.dart is necessary. Marker time is not used to paint the path and marker info is not output to pre-generated paths.

**Comment by bckircher** [comment]
Correct, it is not used at present. It will be used by something I'm working on though. My thinking was to put all the marker time computation changes into a single PR, but I can pull the path_painter_util.dart part out and put that into the other PR if you'd prefer.

And path_painter_util.dart doesn't feel like the right place for it anyway...but trajectory.dart doesn't match the Java/C++ equivalents (structurally anyway).

**Comment by mjansen4857** [comment]
Then you’d want to add the time field to the EventMarker class in robot_path.dart and calculate all the markers whenever the path is generated. It’s probably best to move that method to a private method of RobotPath then since it doesn’t really have anything to do with the path painter. What’s do you plan on doing with it? Adding it to pre-generated files?

**Comment by bckircher** [comment]
OK, makes sense. Let me go away and re-formulate this and re-submit it.

Here's what I'm working on:

image

The marker times are needed to place them in the correct position across the top of this graph (in this example, I have markers at 0, 0.1, 0.2, ..., 0.9, 1.0).

Of course, it displays the appropriate traces for holonomic vs. non-holonomic modes.

**Comment by mjansen4857** [comment]
Looks awesome. I was thinking of doing something similar to this at some point so that's a huge help. I know you're still working on it so some of this might already be done but I have a few suggestions I can think of at the moment:
- Always show the generator settings card in this editor mode so settings settings can be changed without switching mode (like how it works with the preview mode)
- Click on the labels (velocity, heading, etc.) to toggle showing/hiding them on the graph to make it easier to look at specific values (if you're using a package for the graph it might not let you do this easily so not a huge deal)
- Maybe a subtle dotted line extending down from each marker (again, not a huge deal if the package makes this difficult)

Overall, looks great. Thanks!

**Comment by bckircher** [comment]
Glad you like it! I'm a noob w.r.t Dart (C++ at work, Java with the team), so this is entirely hand-written (for better or worse!). So:

- Adding the generator settings card...should be easy (just lift it from the preview editor).
- Click on the labels...completely agree and already in the process of making that happen!
- Dotted line on the marker...great idea!

**Comment by bckircher** [comment]
OK, the marker time calculation has been moved out of path_painter_util.dart and into trajectory.dart (reasonably in line with what is done in the Java/C++ version). The marker time is stored EventMarker (in robot_path.dart) using a "hidden" field (doesn't show up in the constructor, Json, toString, etc., since it is a derived/computed value).

Happy to make further changes if something is still amiss!

**Pull request merged**
