### PR TITLE
feat: add edit path button in auto editor

### LINKED ISSUE #393: Add button to edit paths from auto editor

### PR DESCRIPTION
**Pull request by hadley31**
Closes #393

### CODE REVIEW

**Comment by mjansen4857** [comment]
So one thing I noticed that might be a bit nicer is if instead of using the `OpenPathCallback` you made that passes a build context around, just pass the path name. You should be able to access the project page context within the _openPathByName method by using `this.context`;

**Comment by hadley31** [comment]
> So one thing I noticed that might be a bit nicer is if instead of using the `OpenPathCallback` you made that passes a build context around, just pass the path name. You should be able to access the project page context within the _openPathByName method by using `this.context`.


Good call! I was hoping you'd suggest a better alternative 😄 I was under the impression I'd need at least the auto editor page context for it to work as I expected, but it makes sense that you could just use the project page context.

> Edit: Also, these changes are difficult to properly test since it depends on some coupling between the project page, auto editor, and path editor. I still haven't gotten around to doing a full integration test like that, so you can ignore those missed lines in project_page. Covering the icon button in path_command_widget shouldn't be too hard though. There should be plenty of examples in there if you're unfamiliar with flutter testing.


Okay! I'll write some tests for it tomorrow when I get some time.

**Comment by hadley31** [comment]
TODO: If path is renamed in path editor pushed by the auto editor page, name change is not reflected unless user returns to projects page, and re-opens auto page. *DO NOT* reorder paths until this is fixed - app crashes and auto file gets wiped.

**Comment by hadley31** [comment]
Going to close this for now. Haven't had the time to get around to it unfortunately, and from what I remember, there was a lot of Navigator context hoops to jump through to make this work without any looming bugs associated with renaming paths/commands. I'm thinking the slight productivity boost isn't worth the trouble.

**Pull request closed without merging**
